<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\..\..\building-blocks\BookStore.BuildingBlocks\BookStore.BuildingBlocks.csproj" />
    <ProjectReference Include="..\BookStore.NotificationService.Application\BookStore.NotificationService.Application.csproj" />
    <ProjectReference Include="..\BookStore.NotificationService.Domain\BookStore.NotificationService.Domain.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
